name: Deploy to ECS (QA)
on:
 push:
   branches:
     - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: qa

    steps:
    - name: Checkout
      uses: actions/checkout@v3
     
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image tws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 848518183369.dkr.ecr.us-east-1.amazonaws.com 
      run: |
        docker build -t page-ms .
        docker tag page-ms:latest 848518183369.dkr.ecr.us-east-1.amazonaws.com/page-ms:latest
        docker push 848518183369.dkr.ecr.us-east-1.amazonaws.com/page-ms:latest      
